pipeline {
	agent { 
		label 						'cc-runner' 
	}
	
	environment { 
		MODULE_NAME 				= 'kms'
		OS_ARCH 					= 'amd64' 
		TF_LOG 						= 'WARN'
		TF_VER 						= '1.8.5'
	}

	stages {
		stage ('Base Dependencies') {
			steps{
				sh '''
					wget -q https://releases.hashicorp.com/terraform/${TF_VER}/terraform_${TF_VER}_linux_${OS_ARCH}.zip
        			unzip -o terraform_${TF_VER}_linux_${OS_ARCH}.zip
        			sudo cp -rf terraform /usr/local/bin/
        			terraform --version
				'''
			}
		}

		stage ('Feature Branch Dependencies') {
			when { expression {env.GIT_BRANCH =~ "origin/feature/*" || env.GIT_BRANCH =~ "origin/*PR*" } }
			steps {
				sh '''
					curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
					tflint --version

					curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash
					tfsec --version
				'''
			}
		}

		stage ('Master Branch Dependencies') {
			when { expression {env.GIT_BRANCH =~ "origin/master/*" } }
			steps {
				sh '''
					curl -Lo ./terraform-docs.tar.gz https://github.com/terraform-docs/terraform-docs/releases/download/v0.18.0/terraform-docs-v0.18.0-$(uname)-amd64.tar.gz
					tar -xzf terraform-docs.tar.gz
					chmod +x terraform-docs
					sudo mv terraform-docs /usr/local/bin/terraform-docs
					terraform-docs --version
				'''
			}
		}

		stage ('Lint') {
			when { expression {env.GIT_BRANCH =~ "origin/feature/*" || env.GIT_BRANCH =~ "origin/*PR*" } }
			steps {
				sh '''
					tflint \
						--init \
						--config .ci/.tflint.hcl 
					tflint \
						-f json \
						--config .ci/.tflint.hcl \
						| tee lint.json
				'''
			}
		}

		stage ('Sec Scanning') {
			when { expression {env.GIT_BRANCH =~ "origin/feature/*" || env.GIT_BRANCH =~ "origin/*PR*" } }
		    steps {
				sh '''
				    tfsec . \
						--format json \
						--no-colour \
						--soft-fail \
						--tfvars-file ./.ci/tests/idengr.tfvars \
						| tee sec.json
				'''
			}
		}

		stage ('Test') {
			when { expression {env.GIT_BRANCH =~ "origin/feature/*" || env.GIT_BRANCH =~ "origin/*PR*" } }
			steps {
				sh '''
					terraform init \
						-no-color
					terraform test \
						-test-directory ./.ci/tests \
						-json | tee test.json || true
				'''
			}
		}
		
		stage ('Document') {
			when { expression {env.GIT_BRANCH =~ "origin/master/*" } }
			steps {
				sh '''
					terraform-docs \
						-c .ci/.tfdocs.yml .
				'''
			}
		}
	}

	post {
        failure {
            emailext body: 'Check console output at $BUILD_URL to view the results. \n\n ${CHANGES} \n\n [JOB-INFO][JOB-INFO][JOB-INFO][JOB-INFO][JOB-INFO][JOB-INFO][JOB-INFO][JOB-INFO][JOB-INFO][JOB-INFO] \n${BUILD_LOG_REGEX,regex="ERROR", escapeHtml=false}',
            to:   EMAIL_LIST,
            subject: 'Build failed in Jenkins: $PROJECT_NAME - #$BUILD_NUMBER'
        }
        success {
            emailext body: 'Check console output at $BUILD_URL to view the results.  \n\n ${CHANGES} \n\n [JOB-INFO][JOB-INFO][JOB-INFO][JOB-INFO][JOB-INFO][JOB-INFO][JOB-INFO][JOB-INFO][JOB-INFO][JOB-INFO] \n${BUILD_LOG, maxLines=100, escapeHtml=false}',
            to:   EMAIL_LIST,
            subject: 'Build succeeded in Jenkins: $PROJECT_NAME - #$BUILD_NUMBER'
        }
    }
}
